#!/bin/bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

yabai -m config external_bar all:32:0

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Loom$" manage=off

echo "yabai configuration loaded..."
