vim.g.mapleader = " " -- change leader to space
vim.g.maplocalleader = " " -- change localleader to space

vim.g.loaded_netrw = 1 -- disable netrw
vim.g.loaded_netrwPlugin = 1 -- disable netrw

local o = vim.opt
o.incsearch = true -- make search act like seach in moder browsers
o.backup = false -- creates backup file
o.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
o.cmdheight = 1 -- more space in the neovim command
o.completeopt = { "menuone", "noselect" } -- mostly just for cmp
o.conceallevel = 0 -- so that `` is visible in markdown files
o.fileencodings = "utf-8" -- the encoding written to a file
o.hlsearch = true -- highlioght all matches on previous search pattern
o.ignorecase = tru -- ignore case in search pattern
o.mouse = "a" -- allow mouse to be used in neovim
o.pumheight = 10 -- popup menu height
o.showmode = false -- we don't need to see things like -- INSERT -- anymore
o.showtabline = 0 -- always show tabs
o.smartcase = true -- smart case
o.smartindent = true -- make indenting smarter again
o.splitbelow = true -- force all horizontal split to go below current window
o.splitright = true -- force all vertical splits to go to the right of the current window
o.swapfile = false -- creates swapfile
o.termguicolors = true -- set term gui colors (most terminals support this)
o.timeoutlen = 1000 -- timeout to wait for mapped sequence to complete (in milliseconds)
o.undofile = true -- enable persistent undo
o.updatetime = 100 -- faster completion (4000ms default)
o.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
o.expandtab = true -- convert tabs to sapces
o.shiftwidth = 2 -- the number of spaces inserted for each indentation
o.cursorline = false -- highlight current line
o.number = true -- set numbered lines
o.breakindent = true -- wrap lines with indent
o.relativenumber = true -- set relative numbered lines
o.numberwidth = 2 -- set number column width to 2 {default 4}
o.signcolumn = "yes" -- always show the sign column, otherwise it would shift the t eaxt each time
o.wrap = false -- disaplay lines as one long line
o.scrolloff = 8 -- makes sure there are always eight lines of context
o.sidescrolloff = 8 -- makes sure there are always eight lines of context
o.showcmd = false -- Don't show the command in the last line
o.ruler = false -- don't show the ruler
o.guifont = "monospace:h17" --  font used in graphical neovim applications
o.title = true -- set the title of window to the value of the titlestring
o.confirm = true -- confirm to save changes before exiting modified buffer
o.fillchars = { eob = " " } -- change the character at the end of buffer
-- o.cursorlineopt = "number" -- set the cursorline
-- o.tabstop = 2 -- insert 2 spaces for a tab
-- o.lastatus = 0 -- Always display the status line
