return {
  mode = { "n", "v" },
  w = { ":w!<CR>", "Save" },
  W = { "<CMD>noautocmd w<CR>", "Save without formatting" },
  q = { ":confirm q<CR>", "Quit" },
  h = { ":nohlsearch<CR>", "No Highlight" },
  p = { require("telescope.builtin").lsp_document_symbols, "Document Symbols" },
  P = { require("telescope.builtin").lsp_dynamic_workspace_symbols, "Workspace Symbols" },
  v = "Go to definition in a split",
  a = "Swap next param",
  f = {
    name = "+Find",
    f = { "<CMD>Telescope find_files<CR>", "Find File <CWD>" },
    h = { "<CMD>Telescope help_tags<CR>", "Find Help" },
    H = { "<CMD>Telescope highlights<CR>", "Find Highlight Groups" },
    M = { "<CMD>Telescope man_pages<CR>", "Man Pages" },
    o = { "<CMD>Telescope oldfiles<CR>", "Open Recent File" },
    R = { "<CMD>Telescope registers<CR>", "Registers" },
    g = { "<CMD>Telescope live_grep<CR>", "Live Grep" },
    G = { "<CMD>Telescope grep_string<CR>", "Grep String" },
    K = { "<CMD>Telescope keymaps<CR>", "Keymaps" },
    C = { "<CMD>Telescope commands<CR>", "Commands" },
    l = { "<CMD>Telescope resume<CR>", "Resume Last Search" },
    c = { "<CMD>Telescope git_commits<CR>", "Git Commits" },
    B = { "<CMD>Telescope git_branches<CR>", "Git Branches" },
    m = { "<CMD>Telescope git_status<CR>", "Git Status" },
    S = { "<CMD>Telescope git_stash<CR>", "Git Stash" },
    e = { "<CMD>Telescope frecency<CR>", "Frecency" },
    b = { "<CMD>Telescope buffers<CR>", "Buffers" },
    d = {
      name = "+DAP",
      c = { "<cmd>Telescope dap commands<cr>", "Dap Commands" },
      b = { "<cmd>Telescope dap list_breakpoints<cr>", "Dap Breakpoints" },
      g = { "<cmd>Telescope dap configurations<cr>", "Dap Configurations" },
      v = { "<cmd>Telescope dap variables<cr>", "Dap Variables" },
      f = { "<cmd>Telescope dap frames<cr>", "Dap Frames" },
    },
  },
  g = {
    name = "+Git",
    g = { ":LazyGit<CR>", "Lazy Git" },
    l = { "<cmd>lua require 'gitsigns'.blame_line()<cr>", "Blame" },
    o = { require("telescope.builtin").git_status, "Open changed file" },
    b = { require("telescope.builtin").git_branches, "Checkout branch" },
    c = { require("telescope.builtin").git_commits, "Checkout commit" },
    C = {
      require("telescope.builtin").git_bcommits,
      "Checkout commit(for current file)",
    },
    U = { ":UndotreeToggle<CR>", "Toggle UndoTree" },
  },
  l = {
    name = "+LSP",
    a = { vim.lsp.buf.code_action, "Code Action" },
    A = { vim.lsp.buf.range_code_action, "Range Code Actions" },
    s = { vim.lsp.buf.signature_help, "Display Signature Information" },
    r = { vim.lsp.buf.rename, "Rename all references" },
    f = { vim.lsp.buf.format, "Format" },
    i = { require("telescope.builtin").lsp_implementations, "Implementation" },
    l = { "<cmd>TroubleToggle document_diagnostics<cr>", "Document Diagnostics (Trouble)" },
    L = { "<cmd>TroubleToggle workspace_diagnostics<cr>", "Workspace Diagnostics (Trouble)" },
    w = { require("telescope.builtin").diagnostics, "Diagnostics" },
    t = { require("telescope").extensions.refactoring.refactors, "Refactor" },
    -- c = { require("config.utils").copyFilePathAndLineNumber, "Copy File Path and Line Number" },

    W = {
      name = "+Workspace",
      a = { vim.lsp.buf.add_workspace_folder, "Add Folder" },
      r = { vim.lsp.buf.remove_workspace_folder, "Remove Folder" },
      l = {
        function()
          print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
        end,
        "List Folders",
      },
    },
  },
  i = {
    name = "Sessions",
    s = { "<cmd>lua require('persistence').load()<cr>", "Load Session" },
    l = { "<cmd>lua require('persistence').load({ last = true })<cr>", "Load Last Session" },
    d = { "<cmd>lua require('persistence').stop()<cr>", "Stop Persistence" },
  },
  r = {
    name = "Replace (Spectre)",
    r = { "<cmd>lua require('spectre').open()<cr>", "Replace" },
    w = { "<cmd>lua require('spectre').open_visual({select_word=true})<cr>", "Replace Word" },
    f = { "<cmd>lua require('spectre').open_file_search()<cr>", "Replace Buffer" },
  },
  T = {
    name = "+Todo",
    t = { "<cmd>TodoTelescope<cr>", "Todo" },
    T = { "<cmd>TodoTelescope keywords=TODO,FIX,FIXME<cr>", "Todo/Fix/Fixme" },
    x = { "<cmd>TodoTrouble<cr>", "Todo (Trouble)" },
    X = { "<cmd>TodoTrouble keywords=TODO,FIX,FIXME<cr><cr>", "Todo/Fix/Fixme (Trouble)" },
  },
  d = {
    name = "Debug",
    b = { require("dap").toggle_breakpoint, "Breakpoint" },
    c = { require("dap").continue, "Continue" },
    i = { require("dap").step_into, "Into" },
    o = { require("dap").step_over, "Over" },
    O = { require("dap").step_out, "Out" },
    r = { require("dap").repl.toggle, "Repl" },
    l = { require("dap").run_last, "Last" },
    u = { require("dapui").toggle, "UI" },
    x = { require("dap").terminate, "Exit" },
  },
  n = {
    name = "+Neogen",
    g = { "<cmd>lua require('neogen').generate()<cr>", "Generate Annotatin" },
    f = { "<cmd>lua require('neogen').generate({ type = 'func' })<cr>", "Generate Function Annotation" },
    t = { "<cmd>lua require('neogen').generate({ type = 'type' })<cr>", "Generate Type Annotation" },
  },
  t = {
    name = "+Tests",
  },
  ["`"] = {
    name = "+Terminal",
    h = { "<CMD>ToggleTerm size=10 direction=horizontal<CR>", "Horizontal" },
    v = { "<CMD>ToggleTerm size=10 direction=vertical<CR>", "Terminal" },
    f = { "<CMD>ToggleTerm direction=float<CR>", "Float" },
  }
}
